# Generated by Django 2.2.6 on 2019-10-04 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('payment_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('pay', models.PositiveIntegerField(default=0)),
                ('change', models.PositiveIntegerField(default=0)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_draft', models.BooleanField(default=True)),
                ('recipe', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicines.Recipe')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
