# Generated by Django 2.2.6 on 2019-10-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='change',
            field=models.IntegerField(default=0),
        ),
    ]
