# Generated by Django 2.2.6 on 2019-10-04 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polyclinics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('patient_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10)),
                ('place_birth', models.CharField(blank=True, max_length=100, null=True)),
                ('date_birth', models.DateField(blank=True, null=True)),
                ('age', models.PositiveIntegerField(default=0)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('blood', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], default='A', max_length=10)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('religion', models.CharField(choices=[('muslim', 'Muslim'), ('catholic', 'Catholic'), ('protestant', 'Protestant'), ('hindu', 'Hindu'), ('buddha', 'Buddha'), ('confucius', 'Conficius')], default='muslim', max_length=100)),
                ('marital', models.CharField(choices=[('married', 'Married'), ('single', 'Single'), ('widow', 'Widow'), ('widower', 'Widower')], default='married', max_length=100)),
                ('is_draft', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('doctor_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.PositiveIntegerField(default=0)),
                ('is_draft', models.BooleanField(default=True)),
                ('poly', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polyclinics.Poly')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
