# Generated by Django 2.2.6 on 2019-10-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyclinics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poly',
            name='name',
            field=models.CharField(default='My Poly', max_length=100),
        ),
    ]
