# Generated by Django 2.2.6 on 2019-10-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyclinics', '0002_auto_20191022_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poly',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
