# Generated by Django 2.2.6 on 2019-10-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyclinics', '0003_auto_20191022_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poly',
            name='name',
            field=models.CharField(default='My Poli', max_length=100),
        ),
    ]
