# Generated by Django 2.2.6 on 2019-10-13 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polyclinics', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='register_date',
        ),
        migrations.AddField(
            model_name='register',
            name='poly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polyclinics.Poly'),
        ),
    ]
