# Generated by Django 2.2.6 on 2019-10-04 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_date',
        ),
    ]
