# Generated by Django 2.2.6 on 2019-10-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_remove_recipe_recipe_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
