# Generated by Django 2.2.6 on 2019-10-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0004_auto_20191016_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
