# Generated by Django 2.2.6 on 2019-10-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0005_auto_20191016_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeitem',
            name='unfulfilled',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
